apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  labels:
    app: nginx
data:
  config.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
      location / {
            root   /app;
            index  index.html index.htm;
        }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
            root   /app;
        }
      location = /basic_status {
        stub_status;
        }
    }