apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics