grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.178.154.222.172.nip.io
  additionalDataSources:
  - name: loki
    editable: false
    jsonData:
        tlsSkipVerify: true
    orgId: 1
    type: loki
    url: http://loki:3100
    version: 1